package: github.com/cncf/servicebroker/k8s/service_controller
import:
- package: github.com/gorilla/mux
  version: ^1.1.0
- package: github.com/satori/go.uuid
  version: ^1.1.0
- package: k8s.io/kubernetes
  version: ^1.4.0-alpha.2
  subpackages:
  - pkg/client/unversioned
