version: 2
requirements:
  signed_off_by:
    required: false
groups:
  admins:
    reset_on_push:
      enabled: true
    approve_by_comment:
      enabled: true
      approve_regex: '(?i)LGTM'
      reject_regex: '(?i)NOT LGTM'
    required: 4
    users:
      - duglin
      - vaikas-google
      - kibbles-n-bytes
      - pmorie
      - fmui
      - zrob
      - tinygrasshopper
      - mattmcneeney
      - n3wscott
